### PR TITLE
[WIP]Whale in a Box

### LINKED ISSUE #3: Push Button JupyterHub on Carina
I'd like to make it dirt simple for someone running a workshop to run JupyterHub on Carina. The idea being that with 1-2 commands they have a fully configured JupyterHub instance setup for them to run their class. No prior knowledge of how to setup and configure JupyterHub required.

* Generate a Let's Encrypt cert, if they have a domain, otherwise a self-signed cert
* JupyterHub is preconfigured with jupyterhub-carina
* Select the user image, and supply templates for the workshop

The end product would look something like this:

1. Create a Carina account and connect to a cluster.
2. Run a single command for one time setup (e.g. figure out your ip address, and make a safe spot for persistent data storage).
3. Note the IP address from the output above and update their DNS.
4. Run a single command to run the JupyterHub server.
5. The JupyterHub docker image handles cert generation, etc before starting up JupyterHub.

If we wanted to be super meta, this could be automated by howtowhale. So you'd log into howtowhale, and follow a notebook which walks you through these steps, handling everything for you except updating DNS.

### PR DESCRIPTION
**Pull request by carolynvs**
It amuses me to call this "Whale in a Box" because this is essentially howtowhale deconstructed for anyone to replicate and customize. When I tried making a single Docker image for people to run, I didn't like how it came out because it left important things like SSL certificates as an exercise to the reader.  It would be neat to update howtowhale to use this as a base, so that howtowhale runs on whaleinabox, proving that it works.

You can see the result of running the scripts at [whaleinabox.carolynvs.com](https://whaleinabox.carolynvs.com).

This is the initial prototype (or brain dump). Some instructions are in the README but comments/documentation needs to be fleshed out more, scripts tested/hardened, and possibly explain more potentially useful configuration settings. 

I still need to work out what should be distributed in the repo for people to build locally and customize, and what should be published to Docker Hub. Right now I'm thinking that `demo/jupyterhub`, `demo/proxy`, `demo/letsencrypt` and `demo/data` could be published, leaving `demo/web` and `demo/jupyter` to be copied locally by the user and custom built.

I have placeholders for PowerShell scripts in the doc but won't add them until the bash scripts are how we'd like them. Then I'll make corresponding PowerShell scripts to match.

Closes #3.

/cc @willingc @rgbkrk

### CODE REVIEW

**Comment by rgbkrk** [comment]
Whoa sweet

**Comment by minrk** [comment]
This is **awesome**

**Comment by willingc** [comment]
Cool. Was playing around with it a bit yesterday afternoon :smile:

**Comment by carolynvs** [comment]
🎉  http://whaleinabox.com/install.html 🎉 

The base docker images are in https://github.com/carolynvs/whaleinabox and the user editable files are in https://github.com/carolynvs/whaleinabox-kit. Splitting them out made installation easier, as the user can just download or clone the kit repo.

I wasn't quite certain if there was value in having the jupyterhub-carina docker image available as a standalone docker image defined in this repository? It makes a few assumptions about being par of a larger environment, e.g. you have a domain name, are terminating SSL somewhere else, have mounted a volume to persist the db and cookie secret, etc. If you see value in the standalone docker image, let me know and we can hash out what needs to change so it can be moved here.

**Pull request closed without merging**
